from itertools import groupby
from typing import NamedTuple, Dict, Set

from BaseClasses import ItemClassification


class DredgeItemData(NamedTuple):
    dredge_item_id: str
    classification: ItemClassification
    item_group: str = ""

item_base_id = 3459028911689314

item_table: Dict[str, DredgeItemData] = {
    "Anchovy King": DredgeItemData("anchovy-ab-1", ItemClassification.filler, "Fish"),
    "Anchovy": DredgeItemData("anchovy", ItemClassification.filler, "Fish"),
    "Bursting Anglerfish": DredgeItemData("anglerfish-ab-1", ItemClassification.filler, "Fish"),
    "Anglerfish": DredgeItemData("anglerfish", ItemClassification.filler, "Fish"),
    "Brood Squid": DredgeItemData("squid-ab-1", ItemClassification.filler, "Fish"),
    "Snag Squid": DredgeItemData("squid-ab-2", ItemClassification.filler, "Fish"),
    "Arrow Squid": DredgeItemData("squid", ItemClassification.filler, "Fish"),
    "Parhelion Jellyfish": DredgeItemData("aurora-jellyfish-ab-1", ItemClassification.filler, "Fish"),
    "Aurora Jellyfish": DredgeItemData("aurora-jellyfish", ItemClassification.filler, "Fish"),
    "Savage Barracuda": DredgeItemData("barracuda-ab-1", ItemClassification.filler, "Fish"),
    "Concertina Barracuda": DredgeItemData("barracuda-ab-2", ItemClassification.filler, "Fish"),
    "Barracuda": DredgeItemData("barracuda", ItemClassification.filler, "Fish"),
    "Voideye": DredgeItemData("barreleye-ab-1", ItemClassification.filler, "Fish"),
    "Barreleye": DredgeItemData("barreleye", ItemClassification.filler, "Fish"),
    "Tusked Grouper": DredgeItemData("black-grouper-ab-1", ItemClassification.filler, "Fish"),
    "Voltaic Grouper": DredgeItemData("black-grouper-ab-2", ItemClassification.filler, "Fish"),
    "Black Grouper": DredgeItemData("black-grouper", ItemClassification.filler, "Fish"),
    "Scouring Bass": DredgeItemData("black-sea-bass-ab-1", ItemClassification.filler, "Fish"),
    "Black Sea Bass": DredgeItemData("black-sea-bass", ItemClassification.filler, "Fish"),
    "Razormouth Tuna": DredgeItemData("blackfin-tuna-ab-1", ItemClassification.filler, "Fish"),
    "Blackfin Tuna": DredgeItemData("blackfin-tuna", ItemClassification.filler, "Fish"),
    "Decaying Blackmouth": DredgeItemData("blackmouth-salmon-ab-1", ItemClassification.filler, "Fish"),
    "Blackmouth Salmon": DredgeItemData("blackmouth-salmon", ItemClassification.filler, "Fish"),
    "Cleft-mouth Shark": DredgeItemData("blacktip-reef-shark-ab-1", ItemClassification.filler, "Fish"),
    "Blacktip Reef Shark": DredgeItemData("blacktip-reef-shark", ItemClassification.filler, "Fish"),
    "Blue Mackerel": DredgeItemData("mackerel", ItemClassification.filler, "Fish"),
    "Bloodskin Shark": DredgeItemData("bronze-whaler-ab-1", ItemClassification.filler, "Fish"),
    "Bronze Whaler": DredgeItemData("bronze-whaler", ItemClassification.filler, "Fish"),
    "Nightwing Catfish": DredgeItemData("catfish-ab-1", ItemClassification.filler, "Fish"),
    "Catfish": DredgeItemData("catfish", ItemClassification.filler, "Fish"),
    "All-Seeing Cod": DredgeItemData("cod-ab-1", ItemClassification.filler, "Fish"),
    "Fanged Cod": DredgeItemData("cod-ab-2", ItemClassification.filler, "Fish"),
    "Three-Headed Cod": DredgeItemData("cod-ab-3", ItemClassification.filler, "Fish"),
    "Cod": DredgeItemData("cod", ItemClassification.filler, "Fish"),
    "Coelacanth": DredgeItemData("coelacanth", ItemClassification.filler, "Fish"),
    "Sprouting Eel": DredgeItemData("conger-eel-ab-1", ItemClassification.filler, "Fish"),
    "Conger Eel": DredgeItemData("conger-eel", ItemClassification.filler, "Fish"),
    "Consumed Grouper": DredgeItemData("coral-grouper-ab-1", ItemClassification.filler, "Fish"),
    "Coral Grouper": DredgeItemData("coral-grouper", ItemClassification.filler, "Fish"),
    "Entangled Crab": DredgeItemData("blue-crab-ab-1", ItemClassification.filler, "Fish"),
    "Blue Crab": DredgeItemData("blue-crab", ItemClassification.filler, "Fish"),
    "Cerebral Crab": DredgeItemData("crab-ab-1", ItemClassification.filler, "Fish"),
    "Common Crab": DredgeItemData("crab", ItemClassification.filler, "Fish"),
    "Crown of Nadir": DredgeItemData("crown-of-thorns-ab-1", ItemClassification.filler, "Fish"),
    "Crown of Thorns": DredgeItemData("crown-of-thorns", ItemClassification.filler, "Fish"),
    "Cortex Decorator": DredgeItemData("decorator-crab-ab-1", ItemClassification.filler, "Fish"),
    "Decorator Crab": DredgeItemData("decorator-crab", ItemClassification.filler, "Fish"),
    "Malignant Pincer": DredgeItemData("fiddler-crab-ab-1", ItemClassification.filler, "Fish"),
    "Fiddler Crab": DredgeItemData("fiddler-crab", ItemClassification.filler, "Fish"),
    "Mire Screecher": DredgeItemData("giant-mud-crab-ab-1", ItemClassification.filler, "Fish"),
    "Giant Mud Crab": DredgeItemData("giant-mud-crab", ItemClassification.filler, "Fish"),
    "Effigy Crab": DredgeItemData("horseshoe-crab-ab-1", ItemClassification.filler, "Fish"),
    "Horseshoe Crab": DredgeItemData("horseshoe-crab", ItemClassification.filler, "Fish"),
    "Splintered Crab": DredgeItemData("rock-crab-ab-1", ItemClassification.filler, "Fish"),
    "Rock Crab": DredgeItemData("rock-crab", ItemClassification.filler, "Fish"),
    "Umbral Puppet": DredgeItemData("spider-crab-ab-1", ItemClassification.filler, "Fish"),
    "Spider Crab": DredgeItemData("spider-crab", ItemClassification.filler, "Fish"),
    "Imperious Lobster": DredgeItemData("spiny-lobster-ab-1", ItemClassification.filler, "Fish"),
    "Spiny Lobster": DredgeItemData("spiny-lobster", ItemClassification.filler, "Fish"),
    "Sable Reacher": DredgeItemData("squat-lobster-ab-1", ItemClassification.filler, "Fish"),
    "Squat Lobster": DredgeItemData("squat-lobster", ItemClassification.filler, "Fish"),
    "Grasping Snail": DredgeItemData("volcano-snail-ab-1", ItemClassification.filler, "Fish"),
    "Volcano Snail": DredgeItemData("volcano-snail", ItemClassification.filler, "Fish"),
    "Infernal Eel": DredgeItemData("cusk-eel-ab-1", ItemClassification.filler, "Fish"),
    "Cusk Eel": DredgeItemData("cusk-eel", ItemClassification.filler, "Fish"),
    "Withered Ray": DredgeItemData("devil-ray-ab-1", ItemClassification.filler, "Fish"),
    "Devil Ray": DredgeItemData("devil-ray", ItemClassification.filler, "Fish"),
    "Bubbling Char": DredgeItemData("char-ab-1", ItemClassification.filler, "Fish"),
    "Char": DredgeItemData("char", ItemClassification.filler, "Fish"),
    "Pale Grasper": DredgeItemData("colossal-squid-ab-1", ItemClassification.filler, "Fish"),
    "Colossal Squid": DredgeItemData("colossal-squid", ItemClassification.filler, "Fish"),
    "Grisly Shark": DredgeItemData("goblin-shark-ab-1", ItemClassification.filler, "Fish"),
    "Goblin Shark": DredgeItemData("goblin-shark", ItemClassification.filler, "Fish"),
    "Fractalline Icefish": DredgeItemData("icefish-ab-1", ItemClassification.filler, "Fish"),
    "Thawed Icefish": DredgeItemData("icefish-ab-2", ItemClassification.filler, "Fish"),
    "Astral Icefish": DredgeItemData("icefish-ab-3", ItemClassification.filler, "Fish"),
    "Icefish": DredgeItemData("icefish", ItemClassification.filler, "Fish"),
    "King's Wreath": DredgeItemData("king-crab-ab-1", ItemClassification.filler, "Fish"),
    "King Crab": DredgeItemData("king-crab", ItemClassification.filler, "Fish"),
    "Feral Lizardfish": DredgeItemData("lizardfish-ab-1", ItemClassification.filler, "Fish"),
    "Lizardfish": DredgeItemData("lizardfish", ItemClassification.filler, "Fish"),
    "Fallen Stars": DredgeItemData("sea-stars-ab-1", ItemClassification.filler, "Fish"),
    "Sea Stars": DredgeItemData("sea-stars", ItemClassification.filler, "Fish"),
    "Sleeper Shark": DredgeItemData("sleeper-shark", ItemClassification.filler, "Fish"),
    "Craterous Seer": DredgeItemData("stargazer-ab-1", ItemClassification.filler, "Fish"),
    "Stargazer": DredgeItemData("stargazer", ItemClassification.filler, "Fish"),
    "Bulbous Toothfish": DredgeItemData("toothfish-ab-1", ItemClassification.filler, "Fish"),
    "Toothfish": DredgeItemData("toothfish", ItemClassification.filler, "Fish"),
    "Hinged Wolffish": DredgeItemData("wolffish-ab-1", ItemClassification.filler, "Fish"),
    "Wolffish": DredgeItemData("wolffish", ItemClassification.filler, "Fish"),
    "Bifurcated Gar": DredgeItemData("abyssal-gar-ab-1", ItemClassification.filler, "Fish"),
    "Abyssal Gar": DredgeItemData("abyssal-gar", ItemClassification.filler, "Fish"),
    "Broken Arapaima": DredgeItemData("arapaima-ab-1", ItemClassification.filler, "Fish"),
    "Arapaima": DredgeItemData("arapaima", ItemClassification.filler, "Fish"),
    "Boreal Shell": DredgeItemData("boreaspis-ab-1", ItemClassification.filler, "Fish"),
    "Boreaspis": DredgeItemData("boreaspis", ItemClassification.filler, "Fish"),
    "Shaper's Prime": DredgeItemData("coelacanth-ab-1", ItemClassification.filler, "Fish"),
    "???": DredgeItemData("deep-form-ab-1", ItemClassification.filler, "Fish"),
    "Excoriated Fiend": DredgeItemData("dunkleosteus-ab-1", ItemClassification.filler, "Fish"),
    "Dunkleosteus": DredgeItemData("dunkleosteus", ItemClassification.filler, "Fish"),
    "Sanguine Shark": DredgeItemData("eagle-shark-ab-1", ItemClassification.filler, "Fish"),
    "Eagle Shark": DredgeItemData("eagle-shark", ItemClassification.filler, "Fish"),
    "Untouchable Wyrmfish": DredgeItemData("giant-dragonfish-ab-1", ItemClassification.filler, "Fish"),
    "Giant Dragonfish": DredgeItemData("giant-dragonfish", ItemClassification.filler, "Fish"),
    "Brute's Crux": DredgeItemData("goliath-tigerfish-ab-1", ItemClassification.filler, "Fish"),
    "Famine's End": DredgeItemData("gulper-eel-ab-1", ItemClassification.filler, "Fish"),
    "Drifting Chrysalis": DredgeItemData("kerygmachela-ab-1", ItemClassification.filler, "Fish"),
    "Kerygmachela": DredgeItemData("kerygmachela", ItemClassification.filler, "Fish"),
    "Silvering Lancetfish": DredgeItemData("lancetfish-ab-1", ItemClassification.filler, "Fish"),
    "Lancetfish": DredgeItemData("lancetfish", ItemClassification.filler, "Fish"),
    "Xeno Xeno": DredgeItemData("mahi-mahi-ab-1", ItemClassification.filler, "Fish"),
    "Mahi Mahi": DredgeItemData("mahi-mahi", ItemClassification.filler, "Fish"),
    "Clutching Nautilus": DredgeItemData("nautilus-ab-1", ItemClassification.filler, "Fish"),
    "Nautilus": DredgeItemData("nautilus", ItemClassification.filler, "Fish"),
    "Wretched Nipper": DredgeItemData("nipponites-ab-1", ItemClassification.filler, "Fish"),
    "Nipponites": DredgeItemData("nipponites", ItemClassification.filler, "Fish"),
    "Archon's Burden": DredgeItemData("oarfish-ab-1", ItemClassification.filler, "Fish"),
    "Crawling Instar": DredgeItemData("opabinia-ab-1", ItemClassification.filler, "Fish"),
    "Opabinia": DredgeItemData("opabinia", ItemClassification.filler, "Fish"),
    "Plated Osteostracan": DredgeItemData("osteostracan-ab-1", ItemClassification.filler, "Fish"),
    "Osteostracan": DredgeItemData("osteostracan", ItemClassification.filler, "Fish"),
    "Anvilfish": DredgeItemData("paddlefish-ab-1", ItemClassification.filler, "Fish"),
    "Paddlefish": DredgeItemData("paddlefish", ItemClassification.filler, "Fish"),
    "Plated Barbjaw": DredgeItemData("sawfish-ab-1", ItemClassification.filler, "Fish"),
    "Sawfish": DredgeItemData("sawfish", ItemClassification.filler, "Fish"),
    "Inverted Husk": DredgeItemData("sea-cucumber-ab-1", ItemClassification.filler, "Fish"),
    "Sea Cucumber": DredgeItemData("sea-cucumber", ItemClassification.filler, "Fish"),
    "Erupting Scorpion": DredgeItemData("sea-scorpion-ab-1", ItemClassification.filler, "Fish"),
    "Sea Scorpion": DredgeItemData("sea-scorpion", ItemClassification.filler, "Fish"),
    "Mimic Slug": DredgeItemData("sea-slug-ab-1", ItemClassification.filler, "Fish"),
    "Sea Slug": DredgeItemData("sea-slug", ItemClassification.filler, "Fish"),
    "Sleeper's Torment": DredgeItemData("sleeper-shark-ab-1", ItemClassification.filler, "Fish"),
    "Vagrant Sollasina": DredgeItemData("sollasina-ab-1", ItemClassification.filler, "Fish"),
    "Sollasina": DredgeItemData("sollasina", ItemClassification.filler, "Fish"),
    "Ivory Impaler": DredgeItemData("swordfish-ab-1", ItemClassification.filler, "Fish"),
    "Swordfish": DredgeItemData("swordfish", ItemClassification.filler, "Fish"),
    "Cystic Trilobite": DredgeItemData("trilobite-ab-1", ItemClassification.filler, "Fish"),
    "Trilobite": DredgeItemData("trilobite", ItemClassification.filler, "Fish"),
    "Stalking Spiderfish": DredgeItemData("tripod-spiderfish-ab-1", ItemClassification.filler, "Fish"),
    "Tripod Spiderfish": DredgeItemData("tripod-spiderfish", ItemClassification.filler, "Fish"),
    "Axial Matron": DredgeItemData("tullimonstrum-ab-1", ItemClassification.filler, "Fish"),
    "Tullimonstrum": DredgeItemData("tullimonstrum", ItemClassification.filler, "Fish"),
    "Unveiled Vetulicolia": DredgeItemData("vetulicolia-ab-1", ItemClassification.filler, "Fish"),
    "Vetulicolia": DredgeItemData("vetulicolia", ItemClassification.filler, "Fish"),
    "Primordial Shadow": DredgeItemData("xiphactinus-ab-1", ItemClassification.filler, "Fish"),
    "Xiphactinus": DredgeItemData("xiphactinus", ItemClassification.filler, "Fish"),
    "Cursed Fangtooth": DredgeItemData("fangtooth-ab-1", ItemClassification.filler, "Fish"),
    "Fangtooth": DredgeItemData("fangtooth", ItemClassification.filler, "Fish"),
    "Radiant Squid": DredgeItemData("firefly-squid-ab-1", ItemClassification.filler, "Fish"),
    "Firefly Squid": DredgeItemData("firefly-squid", ItemClassification.filler, "Fish"),
    "Twisted Shark": DredgeItemData("frilled-shark-ab-1", ItemClassification.filler, "Fish"),
    "Frilled Shark": DredgeItemData("frilled-shark", ItemClassification.filler, "Fish"),
    "Clawfin Gar": DredgeItemData("gar-ab-1", ItemClassification.filler, "Fish"),
    "Grinning Gar": DredgeItemData("gar-ab-2", ItemClassification.filler, "Fish"),
    "Gar": DredgeItemData("gar", ItemClassification.filler, "Fish"),
    "Rapt Shark": DredgeItemData("ghost-shark-ab-1", ItemClassification.filler, "Fish"),
    "Ghost Shark": DredgeItemData("ghost-shark", ItemClassification.filler, "Fish"),
    "Ruptured Vessel": DredgeItemData("giant-amphipod-ab-1", ItemClassification.filler, "Fish"),
    "Giant Amphipod": DredgeItemData("giant-amphipod", ItemClassification.filler, "Fish"),
    "Medusa Octopus": DredgeItemData("glowing-octopus-ab-1", ItemClassification.filler, "Fish"),
    "Glowing Octopus": DredgeItemData("glowing-octopus", ItemClassification.filler, "Fish"),
    "Goliath Tigerfish": DredgeItemData("goliath-tigerfish", ItemClassification.filler, "Fish"),
    "Barbed Eel": DredgeItemData("eel-ab-1", ItemClassification.filler, "Fish"),
    "Host Eel": DredgeItemData("eel-ab-2", ItemClassification.filler, "Fish"),
    "Grey Eel": DredgeItemData("eel", ItemClassification.filler, "Fish"),
    "Entwined Mullet": DredgeItemData("grey-mullet-ab-1", ItemClassification.filler, "Fish"),
    "Gleaming Mullet": DredgeItemData("grey-mullet-ab-2", ItemClassification.filler, "Fish"),
    "Grey Mullet": DredgeItemData("grey-mullet", ItemClassification.filler, "Fish"),
    "Cyclopean Flounder": DredgeItemData("flounder-ab-1", ItemClassification.filler, "Fish"),
    "Riddled Flounder": DredgeItemData("flounder-ab-2", ItemClassification.filler, "Fish"),
    "Gulf Flounder": DredgeItemData("flounder", ItemClassification.filler, "Fish"),
    "Gulper Eel": DredgeItemData("gulper-eel", ItemClassification.filler, "Fish"),
    "Gazing Shark": DredgeItemData("hammerhead-shark-ab-1", ItemClassification.filler, "Fish"),
    "Hammerhead Shark": DredgeItemData("hammerhead-shark", ItemClassification.filler, "Fish"),
    "Twinned Eels": DredgeItemData("longfin-eel-ab-1", ItemClassification.filler, "Fish"),
    "Longfin Eel": DredgeItemData("longfin-eel", ItemClassification.filler, "Fish"),
    "Perished Loosejaw": DredgeItemData("stoplight-loosejaw-ab-1", ItemClassification.filler, "Fish"),
    "Loosejaw": DredgeItemData("stoplight-loosejaw", ItemClassification.filler, "Fish"),
    "Grotesque Mackerel": DredgeItemData("mackerel-ab-1", ItemClassification.filler, "Fish"),
    "Lumpy Mackerel": DredgeItemData("mackerel-ab-2", ItemClassification.filler, "Fish"),
    "Many-Eyed Mackerel": DredgeItemData("mackerel-ab-3", ItemClassification.filler, "Fish"),
    "Skeletal Moonfish": DredgeItemData("moonfish-ab-1", ItemClassification.filler, "Fish"),
    "Beaked Moonfish": DredgeItemData("moonfish-ab-2", ItemClassification.filler, "Fish"),
    "Moonfish": DredgeItemData("moonfish", ItemClassification.filler, "Fish"),
    "Oarfish": DredgeItemData("oarfish", ItemClassification.filler, "Fish"),
    "Gnashing Perch": DredgeItemData("oceanic-perch-ab-1", ItemClassification.filler, "Fish"),
    "Oceanic Perch": DredgeItemData("oceanic-perch", ItemClassification.filler, "Fish"),
    "Defaced Skate": DredgeItemData("pale-skate-ab-1", ItemClassification.filler, "Fish"),
    "Pale Skate": DredgeItemData("pale-skate", ItemClassification.filler, "Fish"),
    "Congealed Rattail": DredgeItemData("rattail-ab-1", ItemClassification.filler, "Fish"),
    "Rattail": DredgeItemData("rattail", ItemClassification.filler, "Fish"),
    "Blood Snapper": DredgeItemData("red-snapper-ab-1", ItemClassification.filler, "Fish"),
    "Latching Snapper": DredgeItemData("red-snapper-ab-2", ItemClassification.filler, "Fish"),
    "Red Snapper": DredgeItemData("red-snapper", ItemClassification.filler, "Fish"),
    "Sallow Sailfish": DredgeItemData("sailfish-ab-1", ItemClassification.filler, "Fish"),
    "Hooked Sailfish": DredgeItemData("sailfish-ab-2", ItemClassification.filler, "Fish"),
    "Sailfish": DredgeItemData("sailfish", ItemClassification.filler, "Fish"),
    "Leeching Prawn": DredgeItemData("scarlet-prawn-ab-1", ItemClassification.filler, "Fish"),
    "Scarlet Prawn": DredgeItemData("scarlet-prawn", ItemClassification.filler, "Fish"),
    "Ossified Searobin": DredgeItemData("searobin-ab-1", ItemClassification.filler, "Fish"),
    "Armored Searobin": DredgeItemData("searobin", ItemClassification.filler, "Fish"),
    "Vortex Interloper": DredgeItemData("sergeant-fish-ab-1", ItemClassification.filler, "Fish"),
    "Sergeant Fish": DredgeItemData("sergeant-fish", ItemClassification.filler, "Fish"),
    "Calcified Snailfish": DredgeItemData("snailfish-ab-1", ItemClassification.filler, "Fish"),
    "Seizing Snailfish": DredgeItemData("snailfish-ab-2", ItemClassification.filler, "Fish"),
    "Snailfish": DredgeItemData("snailfish", ItemClassification.filler, "Fish"),
    "Serpentine Mackerel": DredgeItemData("snake-mackerel-ab-1", ItemClassification.filler, "Fish"),
    "Tattered Mackerel": DredgeItemData("snake-mackerel-ab-2", ItemClassification.filler, "Fish"),
    "Snake Mackerel": DredgeItemData("snake-mackerel", ItemClassification.filler, "Fish"),
    "Shard Ray": DredgeItemData("stingray-ab-1", ItemClassification.filler, "Fish"),
    "Stingray": DredgeItemData("stingray", ItemClassification.filler, "Fish"),
    "Gelatinous Stonefish": DredgeItemData("stonefish-ab-1", ItemClassification.filler, "Fish"),
    "Enthralled Stonefish": DredgeItemData("stonefish-ab-2", ItemClassification.filler, "Fish"),
    "Stonefish": DredgeItemData("stonefish", ItemClassification.filler, "Fish"),
    "Translucent Sturgeon": DredgeItemData("sturgeon-ab-1", ItemClassification.filler, "Fish"),
    "Sturgeon": DredgeItemData("sturgeon", ItemClassification.filler, "Fish"),
    "Charred Sunfish": DredgeItemData("sunfish-ab-1", ItemClassification.filler, "Fish"),
    "Glaring Sunfish": DredgeItemData("sunfish-ab-2", ItemClassification.filler, "Fish"),
    "Ocean Sunfish": DredgeItemData("sunfish", ItemClassification.filler, "Fish"),
    "Blistered Tarpon": DredgeItemData("tarpon-ab-1", ItemClassification.filler, "Fish"),
    "Tarpon": DredgeItemData("tarpon", ItemClassification.filler, "Fish"),
    "Flayed Mackerel": DredgeItemData("tiger-mackerel-ab-1", ItemClassification.filler, "Fish"),
    "Bearded Mackerel": DredgeItemData("tiger-mackerel-ab-2", ItemClassification.filler, "Fish"),
    "Tiger Mackerel": DredgeItemData("tiger-mackerel", ItemClassification.filler, "Fish"),
    "Decrepit Viperfish": DredgeItemData("viperfish-ab-1", ItemClassification.filler, "Fish"),
    "Collapsed Viperfish": DredgeItemData("viperfish-ab-2", ItemClassification.filler, "Fish"),
    "Viperfish": DredgeItemData("viperfish", ItemClassification.filler, "Fish"),
    "Shattered Wreckfish": DredgeItemData("wreckfish-ab-1", ItemClassification.filler, "Fish"),
    "Bony Wreckfish": DredgeItemData("wreckfish-ab-2", ItemClassification.filler, "Fish"),
    "Wreckfish": DredgeItemData("wreckfish", ItemClassification.filler, "Fish"),
    "Ornate Key": DredgeItemData("relic1", ItemClassification.progression, "Relic"),
    "Rusted Music Box": DredgeItemData("relic2", ItemClassification.progression, "Relic"),
    "Jewel Encrusted Band": DredgeItemData("relic3", ItemClassification.progression, "Relic"),
    "Shimmering Necklace": DredgeItemData("relic4", ItemClassification.progression, "Relic"),
    "Antique Pocket Watch": DredgeItemData("relic5", ItemClassification.progression, "Relic"),
}

def get_item_group(item_name: str) -> str:
    return item_table[item_name].item_group


item_name_to_id: Dict[str, int] = {name: item_base_id + index for index, name in enumerate(item_table)}

item_name_groups: Dict[str, Set[str]] = {
    group: set(item_names) for group, item_names in groupby(sorted(item_table, key=get_item_group), get_item_group) if group != ""
}