from typing import Dict, Set, NamedTuple


class DredgeLocationData(NamedTuple):
    dredge_fish_id: str
    region: str
    location_group: str = ""

location_base_id = 3459028911689314

location_table: Dict[str, DredgeLocationData] ={
    "Anchovy King": DredgeLocationData("anchovy-ab-1", "Open Ocean", "Encyclopedia"),
    "Anchovy": DredgeLocationData("anchovy", "Open Ocean", "Encyclopedia"),
    "Bursting Anglerfish": DredgeLocationData("anglerfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Anglerfish": DredgeLocationData("anglerfish", "Open Ocean", "Encyclopedia"),
    "Brood Squid": DredgeLocationData("squid-ab-1", "Open Ocean", "Encyclopedia"),
    "Snag Squid": DredgeLocationData("squid-ab-2", "Open Ocean", "Encyclopedia"),
    "Arrow Squid": DredgeLocationData("squid", "Open Ocean", "Encyclopedia"),
    "Parhelion Jellyfish": DredgeLocationData("aurora-jellyfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Aurora Jellyfish": DredgeLocationData("aurora-jellyfish", "Open Ocean", "Encyclopedia"),
    "Savage Barracuda": DredgeLocationData("barracuda-ab-1", "Open Ocean", "Encyclopedia"),
    "Concertina Barracuda": DredgeLocationData("barracuda-ab-2", "Open Ocean", "Encyclopedia"),
    "Barracuda": DredgeLocationData("barracuda", "Open Ocean", "Encyclopedia"),
    "Voideye": DredgeLocationData("barreleye-ab-1", "Open Ocean", "Encyclopedia"),
    "Barreleye": DredgeLocationData("barreleye", "Open Ocean", "Encyclopedia"),
    "Tusked Grouper": DredgeLocationData("black-grouper-ab-1", "Open Ocean", "Encyclopedia"),
    "Voltaic Grouper": DredgeLocationData("black-grouper-ab-2", "Open Ocean", "Encyclopedia"),
    "Black Grouper": DredgeLocationData("black-grouper", "Open Ocean", "Encyclopedia"),
    "Scouring Bass": DredgeLocationData("black-sea-bass-ab-1", "Open Ocean", "Encyclopedia"),
    "Black Sea Bass": DredgeLocationData("black-sea-bass", "Open Ocean", "Encyclopedia"),
    "Razormouth Tuna": DredgeLocationData("blackfin-tuna-ab-1", "Open Ocean", "Encyclopedia"),
    "Blackfin Tuna": DredgeLocationData("blackfin-tuna", "Open Ocean", "Encyclopedia"),
    "Decaying Blackmouth": DredgeLocationData("blackmouth-salmon-ab-1", "Open Ocean", "Encyclopedia"),
    "Blackmouth Salmon": DredgeLocationData("blackmouth-salmon", "Open Ocean", "Encyclopedia"),
    "Cleft-mouth Shark": DredgeLocationData("blacktip-reef-shark-ab-1", "Open Ocean", "Encyclopedia"),
    "Blacktip Reef Shark": DredgeLocationData("blacktip-reef-shark", "Open Ocean", "Encyclopedia"),
    "Blue Mackerel": DredgeLocationData("mackerel", "Open Ocean", "Encyclopedia"),
    "Bloodskin Shark": DredgeLocationData("bronze-whaler-ab-1", "Open Ocean", "Encyclopedia"),
    "Bronze Whaler": DredgeLocationData("bronze-whaler", "Open Ocean", "Encyclopedia"),
    "Nightwing Catfish": DredgeLocationData("catfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Catfish": DredgeLocationData("catfish", "Open Ocean", "Encyclopedia"),
    "All-Seeing Cod": DredgeLocationData("cod-ab-1", "Open Ocean", "Encyclopedia"),
    "Fanged Cod": DredgeLocationData("cod-ab-2", "Open Ocean", "Encyclopedia"),
    "Three-Headed Cod": DredgeLocationData("cod-ab-3", "Open Ocean", "Encyclopedia"),
    "Cod": DredgeLocationData("cod", "Open Ocean", "Encyclopedia"),
    "Coelacanth": DredgeLocationData("coelacanth", "Open Ocean", "Encyclopedia"),
    "Sprouting Eel": DredgeLocationData("conger-eel-ab-1", "Open Ocean", "Encyclopedia"),
    "Conger Eel": DredgeLocationData("conger-eel", "Open Ocean", "Encyclopedia"),
    "Consumed Grouper": DredgeLocationData("coral-grouper-ab-1", "Open Ocean", "Encyclopedia"),
    "Coral Grouper": DredgeLocationData("coral-grouper", "Open Ocean", "Encyclopedia"),
    "Entangled Crab": DredgeLocationData("blue-crab-ab-1", "Open Ocean", "Encyclopedia"),
    "Blue Crab": DredgeLocationData("blue-crab", "Open Ocean", "Encyclopedia"),
    "Cerebral Crab": DredgeLocationData("crab-ab-1", "Open Ocean", "Encyclopedia"),
    "Common Crab": DredgeLocationData("crab", "Open Ocean", "Encyclopedia"),
    "Crown of Nadir": DredgeLocationData("crown-of-thorns-ab-1", "Open Ocean", "Encyclopedia"),
    "Crown of Thorns": DredgeLocationData("crown-of-thorns", "Open Ocean", "Encyclopedia"),
    "Cortex Decorator": DredgeLocationData("decorator-crab-ab-1", "Open Ocean", "Encyclopedia"),
    "Decorator Crab": DredgeLocationData("decorator-crab", "Open Ocean", "Encyclopedia"),
    "Malignant Pincer": DredgeLocationData("fiddler-crab-ab-1", "Open Ocean", "Encyclopedia"),
    "Fiddler Crab": DredgeLocationData("fiddler-crab", "Open Ocean", "Encyclopedia"),
    "Mire Screecher": DredgeLocationData("giant-mud-crab-ab-1", "Open Ocean", "Encyclopedia"),
    "Giant Mud Crab": DredgeLocationData("giant-mud-crab", "Open Ocean", "Encyclopedia"),
    "Effigy Crab": DredgeLocationData("horseshoe-crab-ab-1", "Open Ocean", "Encyclopedia"),
    "Horseshoe Crab": DredgeLocationData("horseshoe-crab", "Open Ocean", "Encyclopedia"),
    "Splintered Crab": DredgeLocationData("rock-crab-ab-1", "Open Ocean", "Encyclopedia"),
    "Rock Crab": DredgeLocationData("rock-crab", "Open Ocean", "Encyclopedia"),
    "Umbral Puppet": DredgeLocationData("spider-crab-ab-1", "Open Ocean", "Encyclopedia"),
    "Spider Crab": DredgeLocationData("spider-crab", "Open Ocean", "Encyclopedia"),
    "Imperious Lobster": DredgeLocationData("spiny-lobster-ab-1", "Open Ocean", "Encyclopedia"),
    "Spiny Lobster": DredgeLocationData("spiny-lobster", "Open Ocean", "Encyclopedia"),
    "Sable Reacher": DredgeLocationData("squat-lobster-ab-1", "Open Ocean", "Encyclopedia"),
    "Squat Lobster": DredgeLocationData("squat-lobster", "Open Ocean", "Encyclopedia"),
    "Grasping Snail": DredgeLocationData("volcano-snail-ab-1", "Open Ocean", "Encyclopedia"),
    "Volcano Snail": DredgeLocationData("volcano-snail", "Open Ocean", "Encyclopedia"),
    "Infernal Eel": DredgeLocationData("cusk-eel-ab-1", "Open Ocean", "Encyclopedia"),
    "Cusk Eel": DredgeLocationData("cusk-eel", "Open Ocean", "Encyclopedia"),
    "Withered Ray": DredgeLocationData("devil-ray-ab-1", "Open Ocean", "Encyclopedia"),
    "Devil Ray": DredgeLocationData("devil-ray", "Open Ocean", "Encyclopedia"),
    "Bubbling Char": DredgeLocationData("char-ab-1", "Open Ocean", "Encyclopedia"),
    "Char": DredgeLocationData("char", "Open Ocean", "Encyclopedia"),
    "Pale Grasper": DredgeLocationData("colossal-squid-ab-1", "Open Ocean", "Encyclopedia"),
    "Colossal Squid": DredgeLocationData("colossal-squid", "Open Ocean", "Encyclopedia"),
    "Grisly Shark": DredgeLocationData("goblin-shark-ab-1", "Open Ocean", "Encyclopedia"),
    "Goblin Shark": DredgeLocationData("goblin-shark", "Open Ocean", "Encyclopedia"),
    "Fractalline Icefish": DredgeLocationData("icefish-ab-1", "Open Ocean", "Encyclopedia"),
    "Thawed Icefish": DredgeLocationData("icefish-ab-2", "Open Ocean", "Encyclopedia"),
    "Astral Icefish": DredgeLocationData("icefish-ab-3", "Open Ocean", "Encyclopedia"),
    "Icefish": DredgeLocationData("icefish", "Open Ocean", "Encyclopedia"),
    "King's Wreath": DredgeLocationData("king-crab-ab-1", "Open Ocean", "Encyclopedia"),
    "King Crab": DredgeLocationData("king-crab", "Open Ocean", "Encyclopedia"),
    "Feral Lizardfish": DredgeLocationData("lizardfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Lizardfish": DredgeLocationData("lizardfish", "Open Ocean", "Encyclopedia"),
    "Fallen Stars": DredgeLocationData("sea-stars-ab-1", "Open Ocean", "Encyclopedia"),
    "Sea Stars": DredgeLocationData("sea-stars", "Open Ocean", "Encyclopedia"),
    "Sleeper Shark": DredgeLocationData("sleeper-shark", "Open Ocean", "Encyclopedia"),
    "Craterous Seer": DredgeLocationData("stargazer-ab-1", "Open Ocean", "Encyclopedia"),
    "Stargazer": DredgeLocationData("stargazer", "Open Ocean", "Encyclopedia"),
    "Bulbous Toothfish": DredgeLocationData("toothfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Toothfish": DredgeLocationData("toothfish", "Open Ocean", "Encyclopedia"),
    "Hinged Wolffish": DredgeLocationData("wolffish-ab-1", "Open Ocean", "Encyclopedia"),
    "Wolffish": DredgeLocationData("wolffish", "Open Ocean", "Encyclopedia"),
    "Bifurcated Gar": DredgeLocationData("abyssal-gar-ab-1", "Open Ocean", "Encyclopedia"),
    "Abyssal Gar": DredgeLocationData("abyssal-gar", "Open Ocean", "Encyclopedia"),
    "Broken Arapaima": DredgeLocationData("arapaima-ab-1", "Open Ocean", "Encyclopedia"),
    "Arapaima": DredgeLocationData("arapaima", "Open Ocean", "Encyclopedia"),
    "Boreal Shell": DredgeLocationData("boreaspis-ab-1", "Open Ocean", "Encyclopedia"),
    "Boreaspis": DredgeLocationData("boreaspis", "Open Ocean", "Encyclopedia"),
    "Shaper's Prime": DredgeLocationData("coelacanth-ab-1", "Open Ocean", "Encyclopedia"),
    "???": DredgeLocationData("deep-form-ab-1", "Open Ocean", "Encyclopedia"),
    "Excoriated Fiend": DredgeLocationData("dunkleosteus-ab-1", "Open Ocean", "Encyclopedia"),
    "Dunkleosteus": DredgeLocationData("dunkleosteus", "Open Ocean", "Encyclopedia"),
    "Sanguine Shark": DredgeLocationData("eagle-shark-ab-1", "Open Ocean", "Encyclopedia"),
    "Eagle Shark": DredgeLocationData("eagle-shark", "Open Ocean", "Encyclopedia"),
    "Untouchable Wyrmfish": DredgeLocationData("giant-dragonfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Giant Dragonfish": DredgeLocationData("giant-dragonfish", "Open Ocean", "Encyclopedia"),
    "Brute's Crux": DredgeLocationData("goliath-tigerfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Famine's End": DredgeLocationData("gulper-eel-ab-1", "Open Ocean", "Encyclopedia"),
    "Drifting Chrysalis": DredgeLocationData("kerygmachela-ab-1", "Open Ocean", "Encyclopedia"),
    "Kerygmachela": DredgeLocationData("kerygmachela", "Open Ocean", "Encyclopedia"),
    "Silvering Lancetfish": DredgeLocationData("lancetfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Lancetfish": DredgeLocationData("lancetfish", "Open Ocean", "Encyclopedia"),
    "Xeno Xeno": DredgeLocationData("mahi-mahi-ab-1", "Open Ocean", "Encyclopedia"),
    "Mahi Mahi": DredgeLocationData("mahi-mahi", "Open Ocean", "Encyclopedia"),
    "Clutching Nautilus": DredgeLocationData("nautilus-ab-1", "Open Ocean", "Encyclopedia"),
    "Nautilus": DredgeLocationData("nautilus", "Open Ocean", "Encyclopedia"),
    "Wretched Nipper": DredgeLocationData("nipponites-ab-1", "Open Ocean", "Encyclopedia"),
    "Nipponites": DredgeLocationData("nipponites", "Open Ocean", "Encyclopedia"),
    "Archon's Burden": DredgeLocationData("oarfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Crawling Instar": DredgeLocationData("opabinia-ab-1", "Open Ocean", "Encyclopedia"),
    "Opabinia": DredgeLocationData("opabinia", "Open Ocean", "Encyclopedia"),
    "Plated Osteostracan": DredgeLocationData("osteostracan-ab-1", "Open Ocean", "Encyclopedia"),
    "Osteostracan": DredgeLocationData("osteostracan", "Open Ocean", "Encyclopedia"),
    "Anvilfish": DredgeLocationData("paddlefish-ab-1", "Open Ocean", "Encyclopedia"),
    "Paddlefish": DredgeLocationData("paddlefish", "Open Ocean", "Encyclopedia"),
    "Plated Barbjaw": DredgeLocationData("sawfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Sawfish": DredgeLocationData("sawfish", "Open Ocean", "Encyclopedia"),
    "Inverted Husk": DredgeLocationData("sea-cucumber-ab-1", "Open Ocean", "Encyclopedia"),
    "Sea Cucumber": DredgeLocationData("sea-cucumber", "Open Ocean", "Encyclopedia"),
    "Erupting Scorpion": DredgeLocationData("sea-scorpion-ab-1", "Open Ocean", "Encyclopedia"),
    "Sea Scorpion": DredgeLocationData("sea-scorpion", "Open Ocean", "Encyclopedia"),
    "Mimic Slug": DredgeLocationData("sea-slug-ab-1", "Open Ocean", "Encyclopedia"),
    "Sea Slug": DredgeLocationData("sea-slug", "Open Ocean", "Encyclopedia"),
    "Sleeper's Torment": DredgeLocationData("sleeper-shark-ab-1", "Open Ocean", "Encyclopedia"),
    "Vagrant Sollasina": DredgeLocationData("sollasina-ab-1", "Open Ocean", "Encyclopedia"),
    "Sollasina": DredgeLocationData("sollasina", "Open Ocean", "Encyclopedia"),
    "Ivory Impaler": DredgeLocationData("swordfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Swordfish": DredgeLocationData("swordfish", "Open Ocean", "Encyclopedia"),
    "Cystic Trilobite": DredgeLocationData("trilobite-ab-1", "Open Ocean", "Encyclopedia"),
    "Trilobite": DredgeLocationData("trilobite", "Open Ocean", "Encyclopedia"),
    "Stalking Spiderfish": DredgeLocationData("tripod-spiderfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Tripod Spiderfish": DredgeLocationData("tripod-spiderfish", "Open Ocean", "Encyclopedia"),
    "Axial Matron": DredgeLocationData("tullimonstrum-ab-1", "Open Ocean", "Encyclopedia"),
    "Tullimonstrum": DredgeLocationData("tullimonstrum", "Open Ocean", "Encyclopedia"),
    "Unveiled Vetulicolia": DredgeLocationData("vetulicolia-ab-1", "Open Ocean", "Encyclopedia"),
    "Vetulicolia": DredgeLocationData("vetulicolia", "Open Ocean", "Encyclopedia"),
    "Primordial Shadow": DredgeLocationData("xiphactinus-ab-1", "Open Ocean", "Encyclopedia"),
    "Xiphactinus": DredgeLocationData("xiphactinus", "Open Ocean", "Encyclopedia"),
    "Cursed Fangtooth": DredgeLocationData("fangtooth-ab-1", "Open Ocean", "Encyclopedia"),
    "Fangtooth": DredgeLocationData("fangtooth", "Open Ocean", "Encyclopedia"),
    "Radiant Squid": DredgeLocationData("firefly-squid-ab-1", "Open Ocean", "Encyclopedia"),
    "Firefly Squid": DredgeLocationData("firefly-squid", "Open Ocean", "Encyclopedia"),
    "Twisted Shark": DredgeLocationData("frilled-shark-ab-1", "Open Ocean", "Encyclopedia"),
    "Frilled Shark": DredgeLocationData("frilled-shark", "Open Ocean", "Encyclopedia"),
    "Clawfin Gar": DredgeLocationData("gar-ab-1", "Open Ocean", "Encyclopedia"),
    "Grinning Gar": DredgeLocationData("gar-ab-2", "Open Ocean", "Encyclopedia"),
    "Gar": DredgeLocationData("gar", "Open Ocean", "Encyclopedia"),
    "Rapt Shark": DredgeLocationData("ghost-shark-ab-1", "Open Ocean", "Encyclopedia"),
    "Ghost Shark": DredgeLocationData("ghost-shark", "Open Ocean", "Encyclopedia"),
    "Ruptured Vessel": DredgeLocationData("giant-amphipod-ab-1", "Open Ocean", "Encyclopedia"),
    "Giant Amphipod": DredgeLocationData("giant-amphipod", "Open Ocean", "Encyclopedia"),
    "Medusa Octopus": DredgeLocationData("glowing-octopus-ab-1", "Open Ocean", "Encyclopedia"),
    "Glowing Octopus": DredgeLocationData("glowing-octopus", "Open Ocean", "Encyclopedia"),
    "Goliath Tigerfish": DredgeLocationData("goliath-tigerfish", "Open Ocean", "Encyclopedia"),
    "Barbed Eel": DredgeLocationData("eel-ab-1", "Open Ocean", "Encyclopedia"),
    "Host Eel": DredgeLocationData("eel-ab-2", "Open Ocean", "Encyclopedia"),
    "Grey Eel": DredgeLocationData("eel", "Open Ocean", "Encyclopedia"),
    "Entwined Mullet": DredgeLocationData("grey-mullet-ab-1", "Open Ocean", "Encyclopedia"),
    "Gleaming Mullet": DredgeLocationData("grey-mullet-ab-2", "Open Ocean", "Encyclopedia"),
    "Grey Mullet": DredgeLocationData("grey-mullet", "Open Ocean", "Encyclopedia"),
    "Cyclopean Flounder": DredgeLocationData("flounder-ab-1", "Open Ocean", "Encyclopedia"),
    "Riddled Flounder": DredgeLocationData("flounder-ab-2", "Open Ocean", "Encyclopedia"),
    "Gulf Flounder": DredgeLocationData("flounder", "Open Ocean", "Encyclopedia"),
    "Gulper Eel": DredgeLocationData("gulper-eel", "Open Ocean", "Encyclopedia"),
    "Gazing Shark": DredgeLocationData("hammerhead-shark-ab-1", "Open Ocean", "Encyclopedia"),
    "Hammerhead Shark": DredgeLocationData("hammerhead-shark", "Open Ocean", "Encyclopedia"),
    "Twinned Eels": DredgeLocationData("longfin-eel-ab-1", "Open Ocean", "Encyclopedia"),
    "Longfin Eel": DredgeLocationData("longfin-eel", "Open Ocean", "Encyclopedia"),
    "Perished Loosejaw": DredgeLocationData("stoplight-loosejaw-ab-1", "Open Ocean", "Encyclopedia"),
    "Loosejaw": DredgeLocationData("stoplight-loosejaw", "Open Ocean", "Encyclopedia"),
    "Grotesque Mackerel": DredgeLocationData("mackerel-ab-1", "Open Ocean", "Encyclopedia"),
    "Lumpy Mackerel": DredgeLocationData("mackerel-ab-2", "Open Ocean", "Encyclopedia"),
    "Many-Eyed Mackerel": DredgeLocationData("mackerel-ab-3", "Open Ocean", "Encyclopedia"),
    "Skeletal Moonfish": DredgeLocationData("moonfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Beaked Moonfish": DredgeLocationData("moonfish-ab-2", "Open Ocean", "Encyclopedia"),
    "Moonfish": DredgeLocationData("moonfish", "Open Ocean", "Encyclopedia"),
    "Oarfish": DredgeLocationData("oarfish", "Open Ocean", "Encyclopedia"),
    "Gnashing Perch": DredgeLocationData("oceanic-perch-ab-1", "Open Ocean", "Encyclopedia"),
    "Oceanic Perch": DredgeLocationData("oceanic-perch", "Open Ocean", "Encyclopedia"),
    "Defaced Skate": DredgeLocationData("pale-skate-ab-1", "Open Ocean", "Encyclopedia"),
    "Pale Skate": DredgeLocationData("pale-skate", "Open Ocean", "Encyclopedia"),
    "Congealed Rattail": DredgeLocationData("rattail-ab-1", "Open Ocean", "Encyclopedia"),
    "Rattail": DredgeLocationData("rattail", "Open Ocean", "Encyclopedia"),
    "Blood Snapper": DredgeLocationData("red-snapper-ab-1", "Open Ocean", "Encyclopedia"),
    "Latching Snapper": DredgeLocationData("red-snapper-ab-2", "Open Ocean", "Encyclopedia"),
    "Red Snapper": DredgeLocationData("red-snapper", "Open Ocean", "Encyclopedia"),
    "Sallow Sailfish": DredgeLocationData("sailfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Hooked Sailfish": DredgeLocationData("sailfish-ab-2", "Open Ocean", "Encyclopedia"),
    "Sailfish": DredgeLocationData("sailfish", "Open Ocean", "Encyclopedia"),
    "Leeching Prawn": DredgeLocationData("scarlet-prawn-ab-1", "Open Ocean", "Encyclopedia"),
    "Scarlet Prawn": DredgeLocationData("scarlet-prawn", "Open Ocean", "Encyclopedia"),
    "Ossified Searobin": DredgeLocationData("searobin-ab-1", "Open Ocean", "Encyclopedia"),
    "Armored Searobin": DredgeLocationData("searobin", "Open Ocean", "Encyclopedia"),
    "Vortex Interloper": DredgeLocationData("sergeant-fish-ab-1", "Open Ocean", "Encyclopedia"),
    "Sergeant Fish": DredgeLocationData("sergeant-fish", "Open Ocean", "Encyclopedia"),
    "Calcified Snailfish": DredgeLocationData("snailfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Seizing Snailfish": DredgeLocationData("snailfish-ab-2", "Open Ocean", "Encyclopedia"),
    "Snailfish": DredgeLocationData("snailfish", "Open Ocean", "Encyclopedia"),
    "Serpentine Mackerel": DredgeLocationData("snake-mackerel-ab-1", "Open Ocean", "Encyclopedia"),
    "Tattered Mackerel": DredgeLocationData("snake-mackerel-ab-2", "Open Ocean", "Encyclopedia"),
    "Snake Mackerel": DredgeLocationData("snake-mackerel", "Open Ocean", "Encyclopedia"),
    "Shard Ray": DredgeLocationData("stingray-ab-1", "Open Ocean", "Encyclopedia"),
    "Stingray": DredgeLocationData("stingray", "Open Ocean", "Encyclopedia"),
    "Gelatinous Stonefish": DredgeLocationData("stonefish-ab-1", "Open Ocean", "Encyclopedia"),
    "Enthralled Stonefish": DredgeLocationData("stonefish-ab-2", "Open Ocean", "Encyclopedia"),
    "Stonefish": DredgeLocationData("stonefish", "Open Ocean", "Encyclopedia"),
    "Translucent Sturgeon": DredgeLocationData("sturgeon-ab-1", "Open Ocean", "Encyclopedia"),
    "Sturgeon": DredgeLocationData("sturgeon", "Open Ocean", "Encyclopedia"),
    "Charred Sunfish": DredgeLocationData("sunfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Glaring Sunfish": DredgeLocationData("sunfish-ab-2", "Open Ocean", "Encyclopedia"),
    "Ocean Sunfish": DredgeLocationData("sunfish", "Open Ocean", "Encyclopedia"),
    "Blistered Tarpon": DredgeLocationData("tarpon-ab-1", "Open Ocean", "Encyclopedia"),
    "Tarpon": DredgeLocationData("tarpon", "Open Ocean", "Encyclopedia"),
    "Flayed Mackerel": DredgeLocationData("tiger-mackerel-ab-1", "Open Ocean", "Encyclopedia"),
    "Bearded Mackerel": DredgeLocationData("tiger-mackerel-ab-2", "Open Ocean", "Encyclopedia"),
    "Tiger Mackerel": DredgeLocationData("tiger-mackerel", "Open Ocean", "Encyclopedia"),
    "Decrepit Viperfish": DredgeLocationData("viperfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Collapsed Viperfish": DredgeLocationData("viperfish-ab-2", "Open Ocean", "Encyclopedia"),
    "Viperfish": DredgeLocationData("viperfish", "Open Ocean", "Encyclopedia"),
    "Shattered Wreckfish": DredgeLocationData("wreckfish-ab-1", "Open Ocean", "Encyclopedia"),
    "Bony Wreckfish": DredgeLocationData("wreckfish-ab-2", "Open Ocean", "Encyclopedia"),
    "Wreckfish": DredgeLocationData("wreckfish", "Open Ocean", "Encyclopedia")
}

standard_location_name_to_id: Dict[str, int] = {name: location_base_id + index for index, name in enumerate(location_table)}

location_name_groups: Dict[str, Set[str]] = {}
for loc_name, loc_data in location_table.items():
    loc_group_name = loc_name.split(" - ", 1)[0]
    location_name_groups.setdefault(loc_group_name, set()).add(loc_name)
    if loc_data.location_group:
        location_name_groups.setdefault(loc_data.location_group, set()).add(loc_name)