from typing import Dict, Set, NamedTuple

from worlds.generic.Rules import LocationProgressType as LPT


class DredgeLocationData(NamedTuple):
    region: str
    location_group: str
    expansion: str
    location_progress_type: LPT



location_base_id = 3459028911689314

location_table: Dict[str, DredgeLocationData] ={
    "Anchovy King": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Anchovy": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Bursting Anglerfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Anglerfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Brood Squid": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Snag Squid": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Arrow Squid": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Parhelion Jellyfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Aurora Jellyfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Savage Barracuda": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Concertina Barracuda": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Barracuda": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Voideye": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Barreleye": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Tusked Grouper": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Voltaic Grouper": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Black Grouper": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Scouring Bass": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Black Sea Bass": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Razormouth Tuna": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Blackfin Tuna": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Decaying Blackmouth": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Blackmouth Salmon": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Cleft-mouth Shark": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Blacktip Reef Shark": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Blue Mackerel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Bloodskin Shark": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Bronze Whaler": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Nightwing Catfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Catfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "All-Seeing Cod": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Fanged Cod": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Three-Headed Cod": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Cod": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Coelacanth": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Sprouting Eel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Conger Eel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Consumed Grouper": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Coral Grouper": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Entangled Crab": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Blue Crab": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Cerebral Crab": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Common Crab": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Crown of Nadir": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Crown of Thorns": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Cortex Decorator": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Decorator Crab": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Malignant Pincer": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Fiddler Crab": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Mire Screecher": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Giant Mud Crab": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Effigy Crab": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Horseshoe Crab": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Splintered Crab": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Rock Crab": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Umbral Puppet": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Spider Crab": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Imperious Lobster": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Spiny Lobster": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Sable Reacher": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Squat Lobster": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Grasping Snail": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Volcano Snail": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Infernal Eel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Cusk Eel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Withered Ray": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Devil Ray": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Bubbling Char": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Char": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Pale Grasper": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Colossal Squid": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Grisly Shark": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Goblin Shark": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Fractalline Icefish": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Thawed Icefish": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Astral Icefish": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Icefish": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "King's Wreath": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "King Crab": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Feral Lizardfish": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Lizardfish": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Fallen Stars": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Sea Stars": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Sleeper Shark": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Craterous Seer": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Stargazer": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Bulbous Toothfish": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Toothfish": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Hinged Wolffish": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Wolffish": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Bifurcated Gar": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Abyssal Gar": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Broken Arapaima": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Arapaima": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Boreal Shell": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Boreaspis": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Shaper's Prime": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Excoriated Fiend": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Dunkleosteus": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Sanguine Shark": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Eagle Shark": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Untouchable Wyrmfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Giant Dragonfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Brute's Crux": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Famine's End": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Drifting Chrysalis": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Kerygmachela": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Silvering Lancetfish": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Lancetfish": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Xeno Xeno": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Mahi Mahi": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Clutching Nautilus": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Nautilus": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Wretched Nipper": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Nipponites": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Archon's Burden": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Crawling Instar": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Opabinia": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Plated Osteostracan": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Osteostracan": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Anvilfish": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Paddlefish": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Plated Barbjaw": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Sawfish": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Inverted Husk": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Sea Cucumber": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Erupting Scorpion": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Sea Scorpion": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Mimic Slug": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Sea Slug": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Sleeper's Torment": DredgeLocationData("Open Ocean", "Encyclopedia", "PaleReach", LPT.DEFAULT),
    "Vagrant Sollasina": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Sollasina": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Ivory Impaler": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Swordfish": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Cystic Trilobite": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Trilobite": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Stalking Spiderfish": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Tripod Spiderfish": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Axial Matron": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Tullimonstrum": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Unveiled Vetulicolia": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Vetulicolia": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Primordial Shadow": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Xiphactinus": DredgeLocationData("Open Ocean", "Encyclopedia", "IronRig", LPT.DEFAULT),
    "Cursed Fangtooth": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Fangtooth": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Radiant Squid": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Firefly Squid": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Twisted Shark": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Frilled Shark": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Clawfin Gar": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Grinning Gar": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Gar": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Rapt Shark": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Ghost Shark": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Ruptured Vessel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Giant Amphipod": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Medusa Octopus": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Glowing Octopus": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Goliath Tigerfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Barbed Eel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Host Eel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Grey Eel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Entwined Mullet": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Gleaming Mullet": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Grey Mullet": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Cyclopean Flounder": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Riddled Flounder": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Gulf Flounder": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Gulper Eel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Gazing Shark": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Hammerhead Shark": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Twinned Eels": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Longfin Eel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Perished Loosejaw": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Loosejaw": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Grotesque Mackerel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Lumpy Mackerel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Many-Eyed Mackerel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Skeletal Moonfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Beaked Moonfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Moonfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Oarfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Gnashing Perch": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Oceanic Perch": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Defaced Skate": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Pale Skate": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Congealed Rattail": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Rattail": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Blood Snapper": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Latching Snapper": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Red Snapper": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Sallow Sailfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Hooked Sailfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Sailfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Leeching Prawn": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Scarlet Prawn": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Ossified Searobin": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Armored Searobin": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Vortex Interloper": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Sergeant Fish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Calcified Snailfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Seizing Snailfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Snailfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Serpentine Mackerel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Tattered Mackerel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Snake Mackerel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Shard Ray": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Stingray": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Gelatinous Stonefish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Enthralled Stonefish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Stonefish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Translucent Sturgeon": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Sturgeon": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Charred Sunfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Glaring Sunfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Ocean Sunfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Blistered Tarpon": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Tarpon": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Flayed Mackerel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Bearded Mackerel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Tiger Mackerel": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Decrepit Viperfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Collapsed Viperfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Viperfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Shattered Wreckfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Bony Wreckfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Wreckfish": DredgeLocationData("Open Ocean", "Encyclopedia", "Base", LPT.DEFAULT),
    "Shop - Simple Skimmer": DredgeLocationData("Open Ocean", "Shop", "Base", LPT.DEFAULT),
    "Shop - Weighted Line": DredgeLocationData("Open Ocean", "Shop", "Base", LPT.DEFAULT),
    "Research - Hydraulic Rod": DredgeLocationData("Open Ocean", "Research", "Base", LPT.DEFAULT),
    "Research - Flexible Fishing Pole": DredgeLocationData("Open Ocean", "Research", "Base", LPT.DEFAULT),
    "Research - Heat Resistant Line": DredgeLocationData("Open Ocean", "Research", "Base", LPT.DEFAULT),
    "Research - Anti-Tangle Line": DredgeLocationData("Open Ocean", "Research", "Base", LPT.DEFAULT),
    "Research - Versatile Rod": DredgeLocationData("Open Ocean", "Research", "Base", LPT.DEFAULT),
    "Research - Harvesting Platform": DredgeLocationData("Open Ocean", "Research", "Base", LPT.DEFAULT),
    "Research - Bottomless Lines": DredgeLocationData("Open Ocean", "Research", "Base", LPT.DEFAULT),
    "Research - Fathomless Winch": DredgeLocationData("Open Ocean", "Research", "Base", LPT.DEFAULT),
    "Quest - Sampling Device": DredgeLocationData("Open Ocean", "Quest", "Base", LPT.DEFAULT),
    "Shop - Barbed Ice Rod": DredgeLocationData("Open Ocean", "Shop", "PaleReach", LPT.DEFAULT),
    "Shop - Glacial Lance": DredgeLocationData("Open Ocean", "Shop", "PaleReach", LPT.DEFAULT),
    "Shop - Infused Rod": DredgeLocationData("Open Ocean", "Shop", "IronRig", LPT.DEFAULT),
    "Shop - Infused Winch": DredgeLocationData("Open Ocean", "Shop", "IronRig", LPT.DEFAULT),
    "Shop - Infused Hoist": DredgeLocationData("Open Ocean", "Shop", "IronRig", LPT.DEFAULT),
    "Shop - Infused Coiling Rod": DredgeLocationData("Open Ocean", "Shop", "IronRig", LPT.DEFAULT),
    "Shop - Infused Fireproof Rod": DredgeLocationData("Open Ocean", "Shop", "IronRig", LPT.DEFAULT),
    "World - Sinew Spindle": DredgeLocationData("Open Ocean", "World", "Base", LPT.DEFAULT),  
    "World - Viscera Crane": DredgeLocationData("Open Ocean", "World", "Base", LPT.DEFAULT),    
    "World - Tendon Rod": DredgeLocationData("Open Ocean", "World", "Base", LPT.DEFAULT),  
    "World - Encrusted Talisman": DredgeLocationData("Open Ocean", "World", "Base", LPT.DEFAULT),
    "Debug1": DredgeLocationData("Open Ocean", "Testing", "Base", LPT.EXCLUDED),
    "Debug2": DredgeLocationData("Open Ocean", "Testing", "Base", LPT.EXCLUDED),
    "Debug3": DredgeLocationData("Open Ocean", "Testing", "Base", LPT.EXCLUDED),
    "Debug4": DredgeLocationData("Open Ocean", "Testing", "Base", LPT.EXCLUDED),
    "Debug5": DredgeLocationData("Open Ocean", "Testing", "Base", LPT.EXCLUDED)
}

location_name_to_id: Dict[str, int] = {name: location_base_id + index for index, name in enumerate(location_table)}

location_name_groups: Dict[str, Set[str]] = {}
for loc_name, loc_data in location_table.items():
    loc_group_name = loc_name.split(" - ", 1)[0]
    location_name_groups.setdefault(loc_group_name, set()).add(loc_name)
    if loc_data.location_group:
        location_name_groups.setdefault(loc_data.location_group, set()).add(loc_name)
