dredge_regions: dict[str, tuple[str]] = {
    "Menu": (
        "Open Ocean",
        "The Marrows",
        "Gale Cliffs",
        "Stellar Basin",
        "Twisted Strand",
        "Devil's Spine",
        "The Iron Rig",
        "The Pale Reach",
    ),
    "Open Ocean": (
        "The Marrows",
        "Gale Cliffs",
        "Stellar Basin",
        "Twisted Strand",
        "Devil's Spine",
        "The Iron Rig",
        "The Pale Reach",
        "Insanity",
    ),
    "The Marrows": ("Shop", "Research"),
    "Gale Cliffs": ("Shop", "Research"),
    "Stellar Basin": ("Shop", "Research"),
    "Twisted Strand": ("Shop", "Research"),
    "Devil's Spine": ("Shop", "Research"),
    "The Pale Reach": ("Shop", "Research"),
    "The Iron Rig": ("Shop", "Research"),
    "Research": tuple(),
    "Shop": tuple(),
    "Insanity": tuple(),
}
